apiVersion: monitors.tks.sh/v1
kind: UptimeRobot
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uptimerobot-sample
spec:
  # Add fields here
  statusPage:
    friendlyName: foo
    # @TODO: Change this
    url: status-foo.examples.com
  hosts:
    - friendlyName: Bar
      url: https://foo.tks.sh
    - friendlyName: Foo
      url: https://bar.tks.sh
  alertContact:
    - id: 1234567
      threshold: 3
      recurrence: 1
    - id: 7654321
      threshold: 1
      recurrence: 1
