apiVersion: monitors.tks.sh/v1
kind: UptimeRobot
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uptimerobot-sample
spec:
  # Add fields here
  name: foo
  hosts:
    - address: foo.tks.sh 
