apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: uptimerobots.monitors.tks.sh
spec:
  group: monitors.tks.sh
  names:
    kind: UptimeRobot
    plural: uptimerobots
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              hosts:
                items:
                  properties:
                    friendlyName:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - url
                  - friendlyName
                  type: object
                type: array
              statusPage:
                properties:
                  friendlyName:
                    type: string
                  url:
                    type: string
                required:
                - url
                - friendlyName
                type: object
            required:
            - statusPage
            - hosts
            type: object
          status:
            properties:
              name:
                type: string
            type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
