---
apiVersion: v1
kind: Secret
metadata:
  name: tks-uptimerobot-controller-secret
  namespace: {{ .Release.Namespace }}
stringData:
  config.yaml: 'uptimerobot-api-key: {{ .Values.secrets.apiKey }}'
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: tks-uptimerobot-controller-webhook-server-secret
  namespace: {{ .Release.Namespace }}
